services:
  - type: web
    name: cloud-sentinel-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    region: oregon
    runtime: python
    branch: main
